version: '3.9'

services:
  frontend:
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    build: https://github.com/cipherem/cipherscan-frontend.git
    env_file:
      -  ../envs/common-frontend.env
